# Configuration file for AutoPR
# Defines settings for automating the optimization process of one or more repositories.

repositories:
  # List of repositories to be processed
  - name: "autopr_test"  # A friendly name for reference purposes
    url: "https://github.com/fabriziosalmi/autopr_test.git"  # Repository URL (should be HTTPS)
    branch: "main"  # Branch to be optimized (default is 'main')
    optimization:
      enable_optimizers: true  # Enable or disable code optimization for this repository
      max_iterations: 5  # Maximum iterations allowed per file for optimization
      ignore_failure: true  # If set to true, failures during optimization will be ignored to continue processing
    paths_to_optimize:
      - "test1.py"  # Specify paths within the repository that should be optimized
    excluded_files:
      - []
    notifications:  # Repository specific notifications (overrides global if provided)
      enable: false
      email:
        recipients:
          - "team@example.com"
        subject: "Optimization Report for example-repo"
        send_on:
          - "failure"  # Send notifications on specific conditions (success, failure)

# General default settings to apply across all repositories unless specified otherwise
default_settings:
  optimization:
    enable_optimizers: true  # Enable optimization by default unless specified per repository
    max_iterations: 10  # Maximum optimization iterations if not defined at the repo level
    ignore_failure: true  # If optimization fails, continue without breaking the process
  paths_to_optimize: ["src/", "lib/"]  # Default paths to optimize unless specified otherwise
  excluded_files: ["README.md"]  # Default list of files to exclude globally

logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  log_to_file: false  # Set to true if logs should be stored in a file
  file_path: "logs/auto_pr.log"  # Path to the log file
  rotation:
    enabled: false  # Rotate logs to prevent a single large log file
    max_size_mb: 10  # Maximum size of a log file before rotation
    backup_count: 5  # Number of old log files to keep

notifications:
  enable: false  # Set to true if notifications are required globally
  email:
    smtp_server: "smtp.example.com"
    port: 587
    use_tls: true
    sender_email: "autopr@example.com"
    recipients:
      - "dev-team@example.com"
    subject: "AutoPR Notification"
    send_on:  # Conditions to send notifications
      - "success"
      - "failure"

retry:
  enabled: true  # Enable retry logic for transient failures
  max_attempts: 3  # Maximum number of retry attempts
  delay_seconds: 60  # Delay between retries

auth:
  use_env_token: true  # Set to true if tokens will be passed via environment variables
  token_name: "GITHUB_ACCESS_TOKEN"  # Name of the token environment variable

# Advanced settings for extensibility and integrations
advanced:
  pre_run_hooks:  # Commands or scripts to run before starting any optimization
    - "scripts/global_pre_hook.sh"
  post_run_hooks:  # Commands or scripts to run after all optimizations are complete
    - "scripts/global_post_hook.sh"

# Reporting settings (optional)
# Define how the reports are generated and stored after optimization
reporting:
  generate_summary: true  # If true, generate a summary report after optimization
  summary_path: "reports/optimization_summary.md"  # Path to the generated summary report
  formats:  # Specify in which formats the reports should be generated
    - "md"
    - "html"
  include_detailed_diff: true  # Include detailed diff of each file in the report
