name: AutoPR Workflow

on:
  workflow_dispatch:  # Manual trigger

jobs:
  auto-pr-job:
    runs-on: ubuntu-latest

    env:
      # Inject GitHub Secrets as Environment Variables for Use in Scripts
      DEFAULT_AUTH_TOKEN: ${{ secrets.DEFAULT_GITHUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget git

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Optimization Script for Example Repo
        env:
          REPO_AUTH_TOKEN: ${{ secrets.EXAMPLE_REPO_ACCESS_TOKEN }}  # Inject repo-specific token
        run: |
          python optimize_script.py --config config.yaml --repo-token $REPO_AUTH_TOKEN

      - name: Run Optimization Script for Another Repo
        env:
          REPO_AUTH_TOKEN: ${{ secrets.ANOTHER_REPO_ACCESS_TOKEN }}
        run: |
          python optimize_script.py --config config.yaml --repo-token $REPO_AUTH_TOKEN
